version: "3"

services:
  web:
    image: sentry:9.1.1
    env_file: .env
    links:
      - postgres
      - redis
    ports:
      - "9000:9000"

  batch:
    image: sentry:9.1.1
    env_file: .env
    command: run cron
    links:
      - postgres
      - redis

  worker:
    image: sentry:9.1.1
    env_file: .env
    command: run worker
    links:
      - postgres
      - redis

  # Middleware
  postgres:
    image: postgres:9.5.18-alpine
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0.5-alpine3.9
    volumes:
      - redis:/data

volumes:
  postgres: {}
  redis: {}
