-DEPLOY-AUTH: ansible-playbook site.yaml --tags "symdon/auth"
-DEPLOY-DEMO-ANGULAR: ansible-playbook site.yaml --tags "symdon/demo-angular"
-DEPLOY-MAILHOG: ansible-playbook site.yaml --tags "symdon/mailhog"
-OPS-DEBUG: ansible-playbook debug.yaml
-OPS-MAIN: ansible-playbook site.yaml
-SERVICE-WEB-WWW: ansible-playbook service-web-www.yaml
-SERVICE-WEB: ansible-playbook service-web.yaml
