---
- user:
    name: "{{ staff.name }}"
    group: "{{ staff.group }}"
    uid: "{{ staff.uid }}"
    state: "{{ staff.state }}"

- authorized_key:
    user: "{{ staff.name }}"
    state: "{{ authorized_key.state }}"
    key: "{{ authorized_key.key }}"
  loop_control:
    loop_var: authorized_key
  with_items: "{{ staff.authorized_keys }}"
