- name: Install redis
  apt:
    name: redis-server
    
- name: Create redis settings directory
  file:
    path: /etc/redis
    state: directory

- name: Create redis settings file
  template:
    src: redis.conf
    dest: /etc/redis/redis.conf
  notify: Reload redis-server
